---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: dev
spec:
  selector:
    app: python
  type: NodePort
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30100
    protocol: TCP
