apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pervol-prod
  namespace: prod
  labels:
    type: local
spec:
  storageClassName: manual-prod
  capacity:
    storage: 0.3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/mydb-prod"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pervolclm-prod
  namespace: prod
spec:
  storageClassName: manual-prod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi
